version: '2.9'

services:
  money-manager:
    container_name: money_manager_run
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      postgresdb:
        condition: service_healthy
    networks:
      - money-manager-net
  postgresdb:
    image: postgres
    container_name: money_manager_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pkg/repository/postgres/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - pgdata:/var/lib/postgresql/money_manager_data
    networks:
      - money-manager-net
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]

networks:
  money-manager-net:
    driver: bridge
volumes:
  pgdata: {}